version: '3'
services:
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:dev
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml